version: '3'

services:

  # lb:

  ######

  influxdb:
    image: influxdb
    ports:
      - 8086:8086 # HTTP API port
      # - 2003:2003 # Graphite (optional)
    environment:
      INFLUXDB_DB: metrics

  influxdb-cli: &influxdb-cli
    image: influxdb
    command:
      - influx
      - -host
      - influxdb
    links:
      - influxdb

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    # environment:
    #   GF_SECURITY_ADMIN_PASSWORD: admin
    #   GF_SERVER_ROOT_URL: http://grafana.server.name
    links:
      - influxdb
